basePath: /ourspb
consumes:
- application/json
definitions:
  AllStoryResponse:
    items:
      properties:
        personName:
          type: string
          x-go-name: PersonName
        portalLink:
          type: string
          x-go-name: PortalLink
        postLink:
          type: string
          x-go-name: PostLink
        story:
          type: string
          x-go-name: Story
      type: object
    type: array
    x-go-package: nats_node/http/model/json
  ApiResponsePersonCount:
    properties:
      message:
        type: string
        x-go-name: Message
      model:
        $ref: '#/definitions/PersonsCountResponse'
      success:
        type: boolean
        x-go-name: Success
    type: object
    x-go-package: nats_node/docs
  ApiResponseSearchPerson:
    properties:
      message:
        type: string
        x-go-name: Message
      model:
        $ref: '#/definitions/PersonsListResponse'
      success:
        type: boolean
        x-go-name: Success
    type: object
    x-go-package: nats_node/docs
  ApiResponseStory:
    properties:
      message:
        type: string
        x-go-name: Message
      model:
        $ref: '#/definitions/AllStoryResponse'
      success:
        type: boolean
        x-go-name: Success
    type: object
    x-go-package: nats_node/docs
  PersonsCountResponse:
    properties:
      count:
        format: int64
        type: integer
        x-go-name: Count
    type: object
    x-go-package: nats_node/http/model/json
  PersonsListResponse:
    properties:
      content:
        items:
          properties:
            awardingDocs:
              items:
                properties:
                  cipher:
                    type: string
                    x-go-name: Cipher
                  docType:
                    type: string
                    x-go-name: DocType
                  images:
                    items:
                      properties:
                        archiveId:
                          format: int64
                          type: integer
                          x-go-name: ArchiveID
                        availableForView:
                          type: boolean
                          x-go-name: AvailableForView
                        availableImagesForView:
                          type: boolean
                          x-go-name: AvailableImagesForView
                        entityId:
                          format: int64
                          type: integer
                          x-go-name: EntityID
                        entityImageId:
                          format: int64
                          type: integer
                          x-go-name: EntityImageID
                        entityKind:
                          type: string
                          x-go-name: EntityKind
                        height:
                          format: int64
                          type: integer
                          x-go-name: Height
                        img:
                          properties:
                            id:
                              format: int64
                              type: integer
                              x-go-name: ID
                            path:
                              type: string
                              x-go-name: Path
                          type: object
                          x-go-name: Img
                        name:
                          type: string
                          x-go-name: Name
                        objectOrder:
                          format: int64
                          type: integer
                          x-go-name: ObjectOrder
                        size:
                          format: int64
                          type: integer
                          x-go-name: Size
                        view:
                          properties:
                            id:
                              format: int64
                              type: integer
                              x-go-name: ID
                            path:
                              type: string
                              x-go-name: Path
                          type: object
                          x-go-name: View
                        width:
                          format: int64
                          type: integer
                          x-go-name: Width
                      type: object
                    type: array
                    x-go-name: Images
                  name:
                    type: string
                    x-go-name: Name
                type: object
              type: array
              x-go-name: AwardingDocs
            awardingPlace:
              type: string
              x-go-name: AwardingPlace
            birthYear:
              format: int64
              type: integer
              x-go-name: BirthYear
            decisionDate:
              type: string
              x-go-name: DecisionDate
            decisionNumber:
              type: string
              x-go-name: DecisionNumber
            docId:
              type: string
              x-go-name: DocID
            documentNumber:
              type: string
              x-go-name: DocumentNumber
            entityId:
              format: int64
              type: integer
              x-go-name: EntityID
            fio:
              type: string
              x-go-name: Fio
            firstName:
              type: string
              x-go-name: FirstName
            joinedFields:
              type: string
              x-go-name: JoinedFields
            lastName:
              type: string
              x-go-name: LastName
            nextDocId:
              type: string
              x-go-name: NextDocID
            patronymic:
              type: string
              x-go-name: Patronymic
            placeOfWork:
              type: string
              x-go-name: PlaceOfWork
            sex:
              type: string
              x-go-name: Sex
          type: object
        type: array
        x-go-name: Content
      total:
        format: int64
        type: integer
        x-go-name: Total
    type: object
    x-go-package: nats_node/http/model/json
host: ourspbapi.spb.dev
info:
  description: API для сервиса - Получения данных через СМЭВ из системы НашСПб
  title: Medal Service.
  version: 1.0.0
paths:
  /GetAllStory:
    get:
      description: GetAllStory позволяет получить весь список мини историй
      operationId: idOfGetAllStoryEndpoint
      responses:
        "200":
          $ref: '#/responses/ApiResponseStory'
      tags:
      - Person
  /GetPersonsCount:
    get:
      description: GetPersonsCount позволяет получить общее количество персоналий
      operationId: idOfGetPersonsCountEndpoint
      responses:
        "200":
          $ref: '#/responses/ApiResponsePersonCount'
      tags:
      - Person
  /GetPersonsCountByName:
    get:
      description: GetPersonsCountByName позволяет получить количество персоналий
        по фамилии
      operationId: idOfGetPersonsCountByNameEndpoint
      parameters:
      - description: фамилия
        example: '"Никонов"'
        in: query
        maxItems: 10
        minItems: 3
        name: name
        required: true
        type: string
        uniqueItems: true
        x-go-name: Name
      responses:
        "200":
          $ref: '#/responses/ApiResponsePersonCount'
      tags:
      - Person
  /SearchPerson:
    get:
      description: SearchPerson позволяет получить информацию о персоне по поисковому
        запросу
      operationId: idOfSearchPersonEndpoint
      parameters:
      - description: страница
        format: int64
        in: query
        name: page
        required: true
        type: integer
        uniqueItems: true
        x-go-name: Page
      - description: размер страницы
        format: int64
        in: query
        name: size
        required: true
        type: integer
        uniqueItems: true
        x-go-name: Size
      - description: ФИО человека
        in: query
        name: fio
        type: string
        uniqueItems: true
        x-go-name: Fio
      - description: Год рождения человека
        format: int64
        in: query
        name: birthYear
        type: integer
        uniqueItems: true
        x-go-name: BirthYear
      - description: Год рождения человека начиная с
        format: int64
        in: query
        name: birthYearFrom
        type: integer
        uniqueItems: true
        x-go-name: BirthYearFrom
      - description: Год рождения человека по
        format: int64
        in: query
        name: birthYearTo
        type: integer
        uniqueItems: true
        x-go-name: BirthYearTo
      - description: Место работы человека
        in: query
        name: placeOfWork
        type: string
        uniqueItems: true
        x-go-name: PlaceOfWork
      - description: Номер документа
        in: query
        name: documentNumber
        type: string
        uniqueItems: true
        x-go-name: DocumentNumber
      responses:
        "200":
          $ref: '#/responses/ApiResponseSearchPerson'
      tags:
      - Person
produces:
- application/json
responses:
  ApiResponsePersonCount:
    description: Модель данных возвращает количество персоналий
    schema:
      $ref: '#/definitions/ApiResponsePersonCount'
  ApiResponseSearchPerson:
    description: Модель данных постранично возвращает информацию о персоне по поисковому
      запросу
    schema:
      $ref: '#/definitions/ApiResponseSearchPerson'
  ApiResponseStory:
    description: Модель данных возвращает массив историй
    schema:
      $ref: '#/definitions/ApiResponseStory'
schemes:
- https
securityDefinitions:
  basic:
    type: basic
swagger: "2.0"
